FROM nginx:stable 
#importa un web server già pronto all'uso

RUN rm -rf /usr/share/nginx/html 
#rimuove file di default o vecchi che si trovano nella cartella html del web server

# COPY static /usr/share/nginx/html 
# mette i file che servono per il frontend dove se li aspetta il web server 


